In [ ]:
print('hi')

hi

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
#with list
data = [1,2,3,4,5]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#with index
s = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
#with dictionary
s2 = pd.Series({'x':100,'y':200,'z':300})
print(s2)

x    100
y    200
z    300
dtype: int64

In [ ]:
# Accessing
data = ['g','e','e','k','s','f','o','r','g','e','e','k','s']
ser = pd.Series(data)
print(ser[::1])

0     g
1     e
2     e
3     k
4     s
5     f
6     o
7     r
8     g
9     e
10    e
11    k
12    s
dtype: object

In [ ]:
#updating
s1 = pd.Series([10,20,30,40],index = ['a','b','c','d'])
print(s1)
#update an element
s1['a']= 99
print(s1)

a    10
b    20
c    30
d    40
dtype: int64
a    99
b    20
c    30
d    40
dtype: int64

In [ ]:
s1.drop('b')
print(s1)
s1=s1.drop('b')
print(s1)

a    99
b    20
c    30
d    40
dtype: int64
a    99
c    30
d    40
dtype: int64

In [ ]:
stu_marks={101:78,102:85,103:92,104:67,105:88}
s=pd.Series(stu_marks)
print(s[103])
s[104]=75
print(s)
s=s.drop(102)
print(s)
s[106]=80
print(s)

92
101    78
102    85
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
dtype: int64
101    78
103    92
104    75
105    88
106    80
dtype: int64

In [ ]:
empid={1001:35000,1002:42000,1003:38000,1004:50000,1005:45000}
s=pd.Series(empid)
s[1003]=40000
print(s)
s=s.drop(1002)
print(s)
s[1006]=55000
print(s[:3])

1001    35000
1002    42000
1003    40000
1004    50000
1005    45000
dtype: int64
1001    35000
1003    40000
1004    50000
1005    45000
dtype: int64
1001    35000
1003    40000
1004    50000
dtype: int64

In [ ]:
product_id=['p101','p102','p103','p104','p105']
price=[500,600,1200,900,1500]
store

In [ ]:
DAY--02

In [ ]:
#Data Frames creation
#using list
import pandas as pd
data = [
    ['Ravi',22,30000],
    ['Priya',24,40000],
    ['Arun',21,28000]
]

df = pd.DataFrame(data,columns=['Name','Age','Salary'])
print(df)

    Name  Age  Salary
0   Ravi   22   30000
1  Priya   24   40000
2   Arun   21   28000

In [ ]:
#using tuple
data = (
    ('Ravi',22,30000),
    ('Priya',24,40000),
    ('Arun',21,28000)
)

df = pd.DataFrame(data,columns=('Name','Age','Salary'))
print(df)

    Name  Age  Salary
0   Ravi   22   30000
1  Priya   24   40000
2   Arun   21   28000

In [ ]:
#using Dict
data = {
    'Name':['Alice','Bob','charlie'],
    'Age':[25,30,35],
    'City':['NY','LA','chicago']
}

df = pd.DataFrame(data)
print(df)

      Name  Age     City
0    Alice   25       NY
1      Bob   30       LA
2  charlie   35  chicago

In [ ]:
#create a dataframe sales and profit of every month in first 6 months of year
data = {
    'Month':['jan','feb','mar','apr','may','june'],
    'Sales':[9000,15000,25000,37000,44000,54000],
    'Profit':[10000,20000,30000,40000,50000,60000]

}
df = pd.DataFrame(data)
print(df)

  Month  Sales  Profit
0   jan   9000   10000
1   feb  15000   20000
2   mar  25000   30000
3   apr  37000   40000
4   may  44000   50000
5  june  54000   60000

In [ ]:
#using set(convert set into list/tuple)
my_set = {100,200,300,400}

df=pd.DataFrame(list(my_set),columns=['Values'])
print(df)

   Values
0     200
1     100
2     400
3     300

In [ ]:
#coverting single series into dataframe
s = pd.Series(
    [1,2,3,4],
    name='Numbers'
)
df = s.to_frame()
df.columns=['digits']#to change the column name from numbers to
print(df)

   digits
0       1
1       2
2       3
3       4

In [ ]:
#converting multiple series into DataFrame
s2 = pd.Series([9,6,5,8])
s3 = pd.Series([12,13,14,15])
d={
    'marks-A':s,
    'marks-B':s2,
    'marks-C':s3
}
df=pd.DataFrame(d)
df.columns=['Marks-A','Marks-B','Marks-C']
print(df)

   Marks-A  Marks-B  Marks-C
0        1        9       12
1        2        6       13
2        3        5       14
3        4        8       15

In [ ]:
#assigning column name
df = pd.DataFrame([
    [1,2],
    [3,4]
])
df.columns=['A','B']
print(df)

   A  B
0  1  2
1  3  4

In [ ]:
#replacing column name
df.rename(columns={'A':'Alpha','B':'Beta'},inplace=True)
print(df)

   Alpha  Beta
0      1     2
1      3     4

In [ ]:
#viewing the DataFrame
s = pd.Series([1,2,3,4])
s2 = pd.Series([9,6,5,8])
s3 = pd.Series([12,13,14,15])
d={
    'marks-A':s,
    'marks-B':s2,
    'marks-C':s3
}
df=pd.DataFrame(d)
df.columns=['Marks-A','Marks-B','Marks-C']
print(df)
#viewing
print(df.head())#count at starting upto 5
print(df.tail())#count from ending upto 5
print(df.head(3))#count from starting upto 3
print(df.tail(2))#count from ending upto 2
print(len(df))#shows the length of rows
print(df.shape)#shows the length of columns
print(df.index)#shows the index
print(df.values)#shows all the values in array

   Marks-A  Marks-B  Marks-C
0        1        9       12
1        2        6       13
2        3        5       14
3        4        8       15
   Marks-A  Marks-B  Marks-C
0        1        9       12
1        2        6       13
2        3        5       14
3        4        8       15
   Marks-A  Marks-B  Marks-C
0        1        9       12
1        2        6       13
2        3        5       14
3        4        8       15
   Marks-A  Marks-B  Marks-C
0        1        9       12
1        2        6       13
2        3        5       14
   Marks-A  Marks-B  Marks-C
2        3        5       14
3        4        8       15
4
(4, 3)
RangeIndex(start=0, stop=4, step=1)
[[ 1  9 12]
 [ 2  6 13]
 [ 3  5 14]
 [ 4  8 15]]

In [ ]:
'''
data = [
    ['Ravi',22,'vizag',30000],
    ['Priya',24,'vzn',40000],
    ['Ravi',22,'vizag',30000],
    ['Priya',24,'vzn',40000],
    ['Arun',21,'hjk',28000]
]

df = pd.DataFrame(data,columns=['Name','Age','city','Salary'])
print(df)'''

    Name  Age   city  Salary
0   Ravi   22  vizag   30000
1  Priya   24    vzn   40000
2   Ravi   22  vizag   30000
3  Priya   24    vzn   40000
4   Arun   21    hjk   28000

In [ ]:
DAY--04

In [ ]:
#Manipulating Data
import pandas as pd

sales = pd.Series(
    [5000,7000,None,8000,9000,10000,None],
    index = [
        'monday','tuesday','wednesday','thursday','friday','saturday','sunday']
                  )
print(sales)

monday        5000.0
tuesday       7000.0
wednesday        NaN
thursday      8000.0
friday        9000.0
saturday     10000.0
sunday           NaN
dtype: float64

In [ ]:
print(sales.min()) #to check minimum value
print(sales.max()) #maximum value
print(sales.mean()) #mean value
print(sales.sum()) #addition/sum
print(sales.var()) #variance
print(sales.std()) #standard deviation
print(sales.dtype) #to check thedata type

5000.0
10000.0
7800.0
39000.0
3700000.0
1923.5384061671346
float64

In [ ]:
#aggregation
sales['tuesday'] = 9500
print(sales)
sales['jan']=None
print(sales)

monday        5000.0
tuesday       9500.0
wednesday        NaN
thursday      8000.0
friday        9000.0
saturday     10000.0
sunday           NaN
dtype: float64
monday        5000.0
tuesday       9500.0
wednesday        NaN
thursday      8000.0
friday        9000.0
saturday     10000.0
sunday           NaN
jan              NaN
dtype: float64

In [ ]:
#deleting data
sales=sales.drop('tuesday')
print(sales)

monday        5000.0
wednesday        NaN
thursday      8000.0
friday        9000.0
saturday     10000.0
sunday           NaN
jan              NaN
dtype: float64

In [ ]:
print(sales + 2000)
print(sales*2)

monday        7000.0
wednesday        NaN
thursday     10000.0
friday       11000.0
saturday     12000.0
sunday           NaN
jan              NaN
dtype: float64
monday       10000.0
wednesday        NaN
thursday     16000.0
friday       18000.0
saturday     20000.0
sunday           NaN
jan              NaN
dtype: float64

In [ ]:
#combinig two Series
s=pd.Series([1,2,3,4,5],index=[9,7,6,8,0])
s1=pd.Series([101,102,103,104,105],index=[901,902,903,904,905])
print(s,s1)
c=pd.concat([s,s1],ignore_index=True)
print(c)
d=pd.concat([s,s1])
print(d)

9    1
7    2
6    3
8    4
0    5
dtype: int64 0    101
1    102
2    103
3    104
4    105
dtype: int64
0      1
1      2
2      3
3      4
4      5
5    101
6    102
7    103
8    104
9    105
dtype: int64
9      1
7      2
6      3
8      4
0      5
0    101
1    102
2    103
3    104
4    105
dtype: int64

In [ ]:
import pandas as pd
data={
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyd","Chennai","Banglore","Hyd","Mumbai","Chennai","Banglore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}

df=pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df.head())

      Name  Age      City  Salary
101   Ravi   22       Hyd   30000
102  Priya   24   Chennai   40000
103   Arun   21  Banglore   28000
104  Sneha   25       Hyd   50000
105  Kiran   23    Mumbai   35000

In [ ]:
#aggreagation of dataframe
print(df['Age'].sum())
print(df['Age'].mean())
print(df['Age'].min())
print(df['Age'].max())
print(df['Age'].var())
print(df['Age'].std())
print(df['Age'].count())

188
23.5
20
27
6.0
2.449489742783178
8

In [ ]:
print(df['Salary'].mean())
print(df['Salary'].min())
print(df['Salary'].max())
print(df['Salary'].sum())
print(df['Salary'].var())
print(df['Salary'].std())
print(df['Salary'].count())

38500.0
25000
55000
308000
118000000.0
10862.780491200216
8

In [ ]:
df['Bonus'] = df['Salary'] *0.10
print(df)

       Name  Age      City  Salary   Bonus
101    Ravi   22       Hyd   30000  3000.0
102   Priya   24   Chennai   40000  4000.0
103    Arun   21  Banglore   28000  2800.0
104   Sneha   25       Hyd   50000  5000.0
105   Kiran   23    Mumbai   35000  3500.0
106  Anjali   26   Chennai   45000  4500.0
107  Vikram   20  Banglore   25000  2500.0
108   Meena   27    Mumbai   55000  5500.0

In [ ]:
df['new_salary'] = df['Salary']+df['Bonus']
print(df)

       Name  Age      City  Salary   Bonus  new_salary
101    Ravi   22       Hyd   30000  3000.0     33000.0
102   Priya   24   Chennai   40000  4000.0     44000.0
103    Arun   21  Banglore   28000  2800.0     30800.0
104   Sneha   25       Hyd   50000  5000.0     55000.0
105   Kiran   23    Mumbai   35000  3500.0     38500.0
106  Anjali   26   Chennai   45000  4500.0     49500.0
107  Vikram   20  Banglore   25000  2500.0     27500.0
108   Meena   27    Mumbai   55000  5500.0     60500.0

In [ ]:
df['Age']=df['Age']+1
print(df)

       Name  Age      City  Salary   Bonus  new_salary
101    Ravi   23       Hyd   30000  3000.0     33000.0
102   Priya   25   Chennai   40000  4000.0     44000.0
103    Arun   22  Banglore   28000  2800.0     30800.0
104   Sneha   26       Hyd   50000  5000.0     55000.0
105   Kiran   24    Mumbai   35000  3500.0     38500.0
106  Anjali   27   Chennai   45000  4500.0     49500.0
107  Vikram   21  Banglore   25000  2500.0     27500.0
108   Meena   28    Mumbai   55000  5500.0     60500.0

In [ ]:
df['Salary']=df['new_salary']-1500
print(df)

       Name  Age      City   Salary   Bonus  new_salary
101    Ravi   23       Hyd  31500.0  3000.0     33000.0
102   Priya   25   Chennai  42500.0  4000.0     44000.0
103    Arun   22  Banglore  29300.0  2800.0     30800.0
104   Sneha   26       Hyd  53500.0  5000.0     55000.0
105   Kiran   24    Mumbai  37000.0  3500.0     38500.0
106  Anjali   27   Chennai  48000.0  4500.0     49500.0
107  Vikram   21  Banglore  26000.0  2500.0     27500.0
108   Meena   28    Mumbai  59000.0  5500.0     60500.0

In [ ]:
df.loc[df['Name']=='Priya','City']='pune'
print(df)

       Name  Age      City   Salary   Bonus  new_salary
101    Ravi   23       Hyd  31500.0  3000.0     33000.0
102   Priya   25      pune  42500.0  4000.0     44000.0
103    Arun   22  Banglore  29300.0  2800.0     30800.0
104   Sneha   26       Hyd  53500.0  5000.0     55000.0
105   Kiran   24    Mumbai  37000.0  3500.0     38500.0
106  Anjali   27   Chennai  48000.0  4500.0     49500.0
107  Vikram   21  Banglore  26000.0  2500.0     27500.0
108   Meena   28    Mumbai  59000.0  5500.0     60500.0

In [ ]:
df.loc[df['City']=='Banglore','City']='HYD'
print(df)

       Name  Age     City   Salary   Bonus  new_salary
101    Ravi   23      Hyd  31500.0  3000.0     33000.0
102   Priya   25     pune  42500.0  4000.0     44000.0
103    Arun   22      HYD  29300.0  2800.0     30800.0
104   Sneha   26      Hyd  53500.0  5000.0     55000.0
105   Kiran   24   Mumbai  37000.0  3500.0     38500.0
106  Anjali   27  Chennai  48000.0  4500.0     49500.0
107  Vikram   21      HYD  26000.0  2500.0     27500.0
108   Meena   28   Mumbai  59000.0  5500.0     60500.0

In [ ]:
df.loc[df['City']=='Mumbai','Salary']=df['Salary']*1.05
print(df)

       Name  Age     City   Salary   Bonus  new_salary
101    Ravi   23      Hyd  31500.0  3000.0     33000.0
102   Priya   25     pune  42500.0  4000.0     44000.0
103    Arun   22      HYD  29300.0  2800.0     30800.0
104   Sneha   26      Hyd  53500.0  5000.0     55000.0
105   Kiran   24   Mumbai  38850.0  3500.0     38500.0
106  Anjali   27  Chennai  48000.0  4500.0     49500.0
107  Vikram   21      HYD  26000.0  2500.0     27500.0
108   Meena   28   Mumbai  61950.0  5500.0     60500.0

In [ ]:
df.loc[df['Salary']<45000,'Salary']=60000
print(df)

       Name  Age     City   Salary   Bonus  new_salary   salary
101    Ravi   23      Hyd  60000.0  3000.0     33000.0  60000.0
102   Priya   25     pune  60000.0  4000.0     44000.0  60000.0
103    Arun   22      HYD  60000.0  2800.0     30800.0  60000.0
104   Sneha   26      Hyd  53500.0  5000.0     55000.0      NaN
105   Kiran   24   Mumbai  60000.0  3500.0     38500.0  60000.0
106  Anjali   27  Chennai  48000.0  4500.0     49500.0      NaN
107  Vikram   21      HYD  60000.0  2500.0     27500.0  60000.0
108   Meena   28   Mumbai  61950.0  5500.0     60500.0      NaN

In [ ]:
df.drop('salary',axis=1,inplace=True)
print(df)

       Name  Age     City   Salary   Bonus  new_salary
101    Ravi   23      Hyd  60000.0  3000.0     33000.0
102   Priya   25     pune  60000.0  4000.0     44000.0
103    Arun   22      HYD  60000.0  2800.0     30800.0
104   Sneha   26      Hyd  53500.0  5000.0     55000.0
105   Kiran   24   Mumbai  60000.0  3500.0     38500.0
106  Anjali   27  Chennai  48000.0  4500.0     49500.0
107  Vikram   21      HYD  60000.0  2500.0     27500.0
108   Meena   28   Mumbai  61950.0  5500.0     60500.0

In [ ]:
df.drop(columns='new_salary',inplace=True)
print(df)

       Name  Age     City   Salary   Bonus
101    Ravi   23      Hyd  60000.0  3000.0
102   Priya   25     pune  60000.0  4000.0
103    Arun   22      HYD  60000.0  2800.0
104   Sneha   26      Hyd  53500.0  5000.0
105   Kiran   24   Mumbai  60000.0  3500.0
106  Anjali   27  Chennai  48000.0  4500.0
107  Vikram   21      HYD  60000.0  2500.0
108   Meena   28   Mumbai  61950.0  5500.0

In [ ]:
--DAY--05

In [ ]:
#loading data from csv,excel files
#to read from csv : df = pd.read_csv('csv-file-name-with-extention) or df = pd.read

In [ ]:
#cleaning the data
#handling missing values
import pandas as pd

df = pd.Series(
    [5000,7000,None,8000,9000,10000,None],
    index = [
        'monday','tuesday','wednesday','thursday','friday','saturday','sunday']
                  )

In [ ]:
#identifying null values
df.isna() #or df.isnull

monday       False
tuesday      False
wednesday     True
thursday     False
friday       False
saturday     False
sunday        True
dtype: bool

In [ ]:
#count of null values
df.isna().sum() #or df.isnull.sum()

np.int64(2)

In [ ]:
#droping the null values
df.dropna()

monday       5000.0
tuesday      7000.0
thursday     8000.0
friday       9000.0
saturday    10000.0
dtype: float64

In [ ]:
#filling missing values
df.fillna('no data')

monday        5000.0
tuesday       7000.0
wednesday    no data
thursday      8000.0
friday        9000.0
saturday     10000.0
sunday       no data
dtype: object

In [ ]:
#replacing the missing values with aggregates

In [ ]:
employees = {
    'EmpID':[101,102,103,104],
    'Name':['Asha',None,'Meena','Sai'],
    'Department':['Sales','IT','HR',None],
    'Salary':[45000,60000,None,89000]
}
I =[901,902,903,904]
df_emp =pd.DataFrame(employees,index = I)
print(df_emp)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df_emp.isna()

     EmpID   Name  Department  Salary
901  False  False       False   False
902  False   True       False   False
903  False  False       False    True
904  False  False        True   False

In [ ]:
df_emp.isna().sum()

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df_emp.fillna({
    'Name':'unknown',
    'Department':'unknown',
    'Salary':0
})

In [ ]:
print(df_emp)

     EmpID     Name Department   Salary
901    101     Asha      Sales  45000.0
902    102  unknown         IT  60000.0
903    103    Meena         HR      0.0
904    104      Sai    unknown  89000.0

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].max())

901    45000.0
902    60000.0
903    89000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].min())

901    45000.0
902    60000.0
903    45000.0
904    89000.0
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].mean())

901    45000.000000
902    60000.000000
903    64666.666667
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].std())

901    45000.000000
902    60000.000000
903    22368.132093
904    89000.000000
Name: Salary, dtype: float64

In [ ]:
df_emp['Salary'].fillna(df_emp['Salary'].var())

901    4.500000e+04
902    6.000000e+04
903    5.003333e+08
904    8.900000e+04
Name: Salary, dtype: float64

In [ ]:
employees = {
    'EmpID':[101,102,103,104],
    'Name':['Asha',None,'Meena','Sai'],
    'Department':['Sales','IT','HR',None],
    'Salary':[45000,60000,None,89000]
}
I =[901,902,903,904]
df =pd.DataFrame(employees,index = I)
print(df_emp)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df.head(2)

     EmpID  Name Department   Salary
901    101  Asha      Sales  45000.0
902    102  None         IT  60000.0

In [ ]:
df.tail(2)

     EmpID   Name Department   Salary
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0

In [ ]:
df[['Name','Salary']]

      Name   Salary
901   Asha  45000.0
902   None  60000.0
903  Meena      NaN
904    Sai  89000.0

In [ ]:
df[df['EmpID']==103]

     EmpID   Name Department  Salary
903    103  Meena         HR     NaN

In [ ]:
df[df["Salary"]>50000]

     EmpID  Name Department   Salary
902    102  None         IT  60000.0
904    104   Sai       None  89000.0

In [ ]:
df[df['Department']=='IT']

     EmpID  Name Department   Salary
902    102  None         IT  60000.0

In [ ]:
df[(df['Name'].isna()) | (df['Department'].isna())]

     EmpID  Name Department   Salary
902    102  None         IT  60000.0
904    104   Sai       None  89000.0

In [ ]:
df.isna().sum()

EmpID         0
Name          1
Department    1
Salary        1
dtype: int64

In [ ]:
df.fillna({
    'Name':'unlnown',
    'Department':'not assigned'
})

     EmpID     Name    Department   Salary
901    101     Asha         Sales  45000.0
902    102  unlnown            IT  60000.0
903    103    Meena            HR      NaN
904    104      Sai  not assigned  89000.0

In [ ]:
df['Bonus']=df['Salary']+df['Salary']*0.10
print(df)

     EmpID   Name Department   Salary    Bonus
901    101   Asha      Sales  45000.0  49500.0
902    102   None         IT  60000.0  66000.0
903    103  Meena         HR      NaN      NaN
904    104    Sai       None  89000.0  97900.0

In [ ]:
--Day-07--

In [ ]:
###
import pandas as pd
employees = {
    'EmpID':[101,102,103,104,105],
    'Name':['Asha',None,'Meena','Sai','Max'],
    'Department':['Sales','IT','HR',None,'Sales'],
    'Salary':[45000,60000,None,89000,90000]
}
I =[901,902,903,904,905]
df =pd.DataFrame(employees,index = I)
print(df)

     EmpID   Name Department   Salary
901    101   Asha      Sales  45000.0
902    102   None         IT  60000.0
903    103  Meena         HR      NaN
904    104    Sai       None  89000.0
905    105    Max      Sales  90000.0

In [ ]:
#cleaning the data
df=df.fillna({
    'Name':'Raj',
    'Department':'unknown',
    'Salary':0
})

In [ ]:
df.groupby('Department')['Salary'].mean()

Department
HR             0.0
IT         60000.0
Sales      67500.0
unknown    89000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].max()

Department
HR             0.0
IT         60000.0
Sales      90000.0
unknown    89000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].min()

Department
HR             0.0
IT         60000.0
Sales      45000.0
unknown    89000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].std()

Department
HR                  NaN
IT                  NaN
Sales      31819.805153
unknown             NaN
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department')['Salary'].agg(['mean','max','min'])

               mean      max      min
Department
HR              0.0      0.0      0.0
IT          60000.0  60000.0  60000.0
Sales       67500.0  90000.0  45000.0
unknown     89000.0  89000.0  89000.0

In [ ]:
df.groupby('Department').agg({
    'EmpID':['mean','max'],
    'Salary':['sum','count']
})

            EmpID         Salary
             mean  max       sum count
Department
HR          103.0  103       0.0     1
IT          102.0  102   60000.0     1
Sales       103.0  105  135000.0     2
unknown     104.0  104   89000.0     1

In [ ]:
data={
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyd","Chennai","Banglore","Hyd","Mumbai","Chennai","Banglore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}

df=pd.DataFrame(data,index=[101,102,103,104,105,106,107,108])
print(df)

       Name  Age      City  Salary
101    Ravi   22       Hyd   30000
102   Priya   24   Chennai   40000
103    Arun   21  Banglore   28000
104   Sneha   25       Hyd   50000
105   Kiran   23    Mumbai   35000
106  Anjali   26   Chennai   45000
107  Vikram   20  Banglore   25000
108   Meena   27    Mumbai   55000

In [ ]:
print(df['Name'])

101      Ravi
102     Priya
103      Arun
104     Sneha
105     Kiran
106    Anjali
107    Vikram
108     Meena
Name: Name, dtype: object

In [ ]:
print(df[['Name','Salary']])

       Name  Salary
101    Ravi   30000
102   Priya   40000
103    Arun   28000
104   Sneha   50000
105   Kiran   35000
106  Anjali   45000
107  Vikram   25000
108   Meena   55000

In [ ]:
print(df[df['Age']>23])

       Name  Age     City  Salary
102   Priya   24  Chennai   40000
104   Sneha   25      Hyd   50000
106  Anjali   26  Chennai   45000
108   Meena   27   Mumbai   55000

In [ ]:
print(df[df['Salary']>40000])

       Name  Age     City  Salary
104   Sneha   25      Hyd   50000
106  Anjali   26  Chennai   45000
108   Meena   27   Mumbai   55000

In [ ]:
print(df[df['City']=='Chennai'])

       Name  Age     City  Salary
102   Priya   24  Chennai   40000
106  Anjali   26  Chennai   45000

In [ ]:
print(df[(df['Age'] >23) & (df['Salary'] > 35000)])

       Name  Age     City  Salary
102   Priya   24  Chennai   40000
104   Sneha   25      Hyd   50000
106  Anjali   26  Chennai   45000
108   Meena   27   Mumbai   55000

In [ ]:
print(df[(df['City']=='Mumbai') | (df['City']=='Bangalore')])

      Name  Age    City  Salary
105  Kiran   23  Mumbai   35000
108  Meena   27  Mumbai   55000

In [ ]:
df[['Name','Salary']][df['Salary']>30000]

       Name  Salary
102   Priya   40000
104   Sneha   50000
105   Kiran   35000
106  Anjali   45000
108   Meena   55000

In [ ]:
df.iloc[1:4]

      Name  Age      City  Salary
102  Priya   24   Chennai   40000
103   Arun   21  Banglore   28000
104  Sneha   25       Hyd   50000

In [ ]:
--DAY-07---

In [ ]:
#Handling Duplicate data
import pandas as pd
data = {
    'EmpID':[101,102,103,104,105,106,107,108,109,110,110],
    'Name':['Ravi','PRIYA','Arun','sneha','Kiran','ANJALI','Vikram','Meena','RAHUL','sneha','sneha'],
    'City':['Hyderabad','hyderabad','CHENNAI','chennai','Bangalore','BANGALORE','Mumbai','mumbai','Delhi','Hyderabad','Hyderabad'],
    'Salary':[30000,40000,3500,4500,32000,50000,38000,42000,36000,45000,45000]
}
df = pd.DataFrame(data)
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   Meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   sneha  Hyderabad   45000
10    110   sneha  Hyderabad   45000

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [ ]:
df[df.duplicated()]

    EmpID   Name       City  Salary
10    110  sneha  Hyderabad   45000

In [ ]:
df[df.duplicated(keep=False)]

    EmpID   Name       City  Salary
9     110  sneha  Hyderabad   45000
10    110  sneha  Hyderabad   45000

In [ ]:
#counting the number of duplicates
df.duplicated().sum()

np.int64(1)

In [ ]:
#extracting duplictes with specified column
d=df[df.duplicated()]
total = d[['Name','Salary']].sum()
print(total)

Name      sneha
Salary    45000
dtype: object

In [ ]:
duplicate_rows = df[df.duplicated(keep=False)]
print(duplicate_rows)

    EmpID   Name       City  Salary
9     110  sneha  Hyderabad   45000
10    110  sneha  Hyderabad   45000

In [ ]:
#extracting the duplicate from one required column(mainly primary key)
df['EmpID'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
Name: EmpID, dtype: bool

In [ ]:
f = df['EmpID'].duplicated(keep=False)
print(f)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
Name: EmpID, dtype: bool

In [ ]:
#dropping duplictes
df.drop_duplicates()
print(df)

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   Meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   sneha  Hyderabad   45000
10    110   sneha  Hyderabad   45000

In [ ]:
#it keeps first duplicate value
df.drop_duplicates(keep='first')

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  hyderabad   40000
2    103    Arun    CHENNAI    3500
3    104   sneha    chennai    4500
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   Meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   sneha  Hyderabad   45000

In [ ]:
#it keeps last duplicate value
df.drop_duplicates(keep='last')

    EmpID    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   Meena     mumbai   42000
8     109   RAHUL      Delhi   36000
10    110   sneha  Hyderabad   45000

In [ ]:
df.drop_duplicates(keep=False)

   EmpID    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  hyderabad   40000
2    103    Arun    CHENNAI    3500
3    104   sneha    chennai    4500
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   Meena     mumbai   42000
8    109   RAHUL      Delhi   36000

In [ ]:
import pandas as pd

data = {

   "TransactionID": [1001, 1002, 1003, 1004, 1005,

                      1006, 1007, 1008, 1009, 1010, 1010, 1011],

   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran",

                "Anjali", "Vikram", "Meena", "Rahul", "Sneha",

                "Sneha", "Kiran"],

   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse",

               "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones",

               "Headphones", "Mouse"],

   "Amount": [55000, 25000, 30000, 5000, 1500,

              2500, 18000, 55000, 22000, 5000,

              5000, 1500]}

df_sales = pd.DataFrame(data)

print(df_sales)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [ ]:
df_sales[df_sales.duplicated()]

    TransactionID Customer     Product  Amount
10           1010    Sneha  Headphones    5000

In [ ]:
df_sales.duplicated().sum()

np.int64(1)

In [ ]:
df_sales.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
dtype: bool

In [ ]:
df_sales.duplicated(keep=False)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11    False
dtype: bool

In [ ]:
amount=df_sales[df_sales.duplicated()]
print(amount['Amount'])

10    5000
Name: Amount, dtype: int64

In [ ]:
df_sales['TransactionID'][df_sales.duplicated()]

10    1010
Name: TransactionID, dtype: int64

In [ ]:
df_sales[df_sales['Customer'].duplicated(keep=False)]

    TransactionID Customer     Product  Amount
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [ ]:
df_sales.drop_duplicates(keep='first')

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500

In [ ]:
data = {

   "VisitID": [501, 502, 503, 504, 505,

               506, 507, 508, 509, 510, 510, 511],

   "Patient": ["Rahul", "Anita", "Suresh", "Priya", "Kiran",

               "Anjali", "Ravi", "Meena", "Arun", "Priya",

               "Priya", "Kiran"],

   "Department": ["Cardiology", "Neurology", "Orthopedic", "General",

                  "Dental", "Cardiology", "Neurology", "General",

                  "Dental", "Cardiology", "Cardiology", "Dental"],

   "BillAmount": [5000, 7500, 4500, 2000, 1500,

                  6000, 7000, 2500, 1800, 6000,6000, 1500]}

df = pd.DataFrame(data)

print(df)

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
dtype: bool

In [ ]:
df[df.duplicated(keep=False)]

    VisitID Patient  Department  BillAmount
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
BillAmount = df[df.duplicated(keep=False)]
print(BillAmount['BillAmount'])

9     6000
10    6000
Name: BillAmount, dtype: int64

In [ ]:
df[df['VisitID'].duplicated()]

    VisitID Patient  Department  BillAmount
10      510   Priya  Cardiology        6000

In [ ]:
df[df['Patient'].duplicated(keep=False)]

    VisitID Patient  Department  BillAmount
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
9       510   Priya  Cardiology        6000
10      510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [ ]:
df.drop_duplicates(keep='first')

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500

In [ ]:
df['VisitID'].drop_duplicates(keep='first')

0     501
1     502
2     503
3     504
4     505
5     506
6     507
7     508
8     509
9     510
11    511
Name: VisitID, dtype: int64

In [49]:
df[['Patient','Department']].drop_duplicates(keep='first')

  Patient  Department
0   Rahul  Cardiology
1   Anita   Neurology
2  Suresh  Orthopedic
3   Priya     General
4   Kiran      Dental
5  Anjali  Cardiology
6    Ravi   Neurology
7   Meena     General
8    Arun      Dental
9   Priya  Cardiology

In [50]:
df.drop_duplicates()

    VisitID Patient  Department  BillAmount
0       501   Rahul  Cardiology        5000
1       502   Anita   Neurology        7500
2       503  Suresh  Orthopedic        4500
3       504   Priya     General        2000
4       505   Kiran      Dental        1500
5       506  Anjali  Cardiology        6000
6       507    Ravi   Neurology        7000
7       508   Meena     General        2500
8       509    Arun      Dental        1800
9       510   Priya  Cardiology        6000
11      511   Kiran      Dental        1500